README.md
varnish/4.1.4/Dockerfile
varnish/4.1.4/varnish_4.1.4.pref
varnish/5.0.0/Dockerfile
varnish/5.0.0/varnish_5.0.0.pref

Varnish 4.1.4 and 5.0.0 are added based on debian. The main purpose it to be used by the CI for varnish integration.

Add varnish images for CI

---

README.md
dd-trace-csharp/0.1.0/Dockerfile

Add a container to provide a test runner for `dd-trace-csharp`.

[dotnet] add dotnet container with Mono

---

README.md
dd-opentracing-cpp/0.1.0/Dockerfile

Adds a base image to use for CI builds of dd-opentracing-cpp.
Builds: https://circleci.com/gh/DataDog/dd-opentracing-cpp/183
Repo: https://github.com/DataDog/dd-opentracing-cpp

[cpp] Add C++ OpenTracing CI build base image

---

dd-opentracing-cpp/build/0.3.1/Dockerfile

Required so we can build nginx-opentracing ourselves, so we can upgrade to the new OpenTracing dynamic loading version without CI breaking and before any nginx-opentracing release supports it.

Adds prereqs for building nginx

---

README.md
snmp/Dockerfile

Add an image for a container running [`smnpsim`](http://snmplabs.com/snmpsim/quickstart.html) to allow for more flexible testing of the SNMP check.

Add snmp image

---

README.md
dd-trace-py/Dockerfile

We add the python tracer test runner to the docker library as we do for other integrations.
Previously, we had an image defined into a `Dockerfile` in our repo but for consistency with other integrations we prefer to have it defined here in our docker library repo.
The main objective of this PR is:
- move the file https://github.com/DataDog/dd-trace-py/blob/168135cdb60ae892addd7b09b30fc71fba772b3a/.circleci/images/runner/Dockerfile to this repo
- move from an ubuntu based image to an alpine based image to save some space
Please note that a build setting has already been added to https://hub.docker.com/r/datadog/docker-library/~/settings/automated-builds/

Add python tracer test runner

---

dd-trace-php/Dockerfile_56

In the [dd-trace-php](https://github.com/DataDog/dd-trace-php) repo we're working on adding an integration for the legacy MongoDB extension in PHP 5 and need to add the extension to the PHP 5.6 container. :)

Add ext/mongo to PHP 5.6

---

dd-trace-py/Dockerfile

This PR updates the `Dockerfile` for `dd-trace-py`.
1. Reorganize commands 
1. Make sure to clean up `apk` cache files in the same `RUN` as `apk add`
2. Install all Python versions in the same `RUN` call
3. Update the versions of Python to the latest patch version
4. Add Python `3.7.1` to the image
1. This is currently not being used by `dd-trace-py`, added for future use
5. Installing [detox](https://pypi.org/project/detox/) `tox` plugin to run test environments in parallel

[dd-trace-py] Update test docker image

---

dd-trace-php/hooks/build

Since we need to build 11 different combinations of Centos version and PHP versions, this PR introduces a way to build and upload all those versions programatically by using Dockerhub's `build/hook` and Docker's build-args feature.

Build and upload  multiple centos images inside hook/build

---

dd-trace-php/Dockerfile_centos
dd-trace-php/hooks/build

Currently dockerhub is in the process of migrating to new repository setup.
The centos build being developed on new repository setups, turned out not to be compatible with legacy setup.
Additionally:
- there was an extra `_` in the tag that slipped through
- Too old Git meant that the images couldn't be used on circleci as  build images (this PR fixes the installation of newer Git)
- this PR adds a way to Re tag original PHP ZTS images as datadog images to make sure that we do not have a rug pulled from under our feet, when something is deprecated/removed in the upstream repository
Note: old repository setups should automatically be upgrade to new over coming months (according to Dockerhub docs)

Fix Centos build broken by incompatibility of legacy dockerhub repository

---

dd-trace-py/Dockerfile

Stay up to date with most patch releases of Python and upgrade Tox to get access to parallel execution mode.

[dd-trace-py] Update Python and Tox versions

---

dd-opentracing-cpp/test/0.3.1/Dockerfile

Putting these things into the base test image.
This makes things nicer while updating and locally testing the integration tests.

[dd-opentracing-cpp] add tools for test container

---

dd-trace-py/Dockerfile

This PR changes the image used by `dd-trace-py` for CI/testing to be based on debian stretch slim instead of alpine.
The reason for this change is so we are more likely to be able to install dependencies from wheels instead of always having to build them from source.
This is going to make a noticeable difference for dependencies like `grpcio` which takes _minutes_ to build and install from source.
Since this is also not alpine based, it gives us a chance to be able to build `manylinux1` wheels for our C-extensions.

[dd-trace-py] Base image on debian instead of alpine

---

dd-trace-py/Dockerfile

We did not have `mysql_config` available so could not build MySQL C-extensions for Python.

[dd-trace-py] Add maridb compat dev package

---

README.md
dd-trace-rb/1.9.3/Dockerfile
dd-trace-rb/2.0.0/Dockerfile
dd-trace-rb/2.1.10/Dockerfile
dd-trace-rb/2.2.10/Dockerfile
dd-trace-rb/2.3.8/Dockerfile
dd-trace-rb/2.4.6/Dockerfile

These images used for testing with dd-trace-rb on CircleCI were using an old version of Bundler that caused dependencies to resolve incorrectly.
This pull request updates the images to a newer version of bundler, so dd-trace-rb can use these updated images to avoid build failures.

Update Bundler to 1.17.3 for dd-trace-rb

---

dd-trace-rb/2.3.7/Dockerfile
dd-trace-rb/2.3.8/Dockerfile

As a follow up from https://github.com/DataDog/docker-library/pull/44, although Bundler 2+ is fine for Ruby 2.3, some libraries (Rails < 5) are not compatible with Bundler 2.0. This PR holds back Bundler for Ruby 2.3 to the 1.x branch.

Fix Ruby 2.3 Bundler to 1.17.3 for dd-trace-rb

---

chef-kitchen/systemd/centos6/Dockerfile

This PR installs python from sources for centos6 and makes the systemd and systemctl fake scripts use python 2.7
The 2 scripts that simulates the behavior of systemd do not work on centos6 as it uses python 2.6 by default.

Fix centos6 image by using python 2.7

---

README.md
chef-kitchen/systemd/centos8/Dockerfile

It adds a new Centos 8 image with a fake systemd for kitchen docker tests on CircleCI
The puppet datadog agent role tests the role against centos 8.

Add Centos8 fake systemd image

---

snmp/Dockerfile
snmp/entrypoint.sh

The snmp container we use for simulating data is using `snmpsim` to serve the content of the fixture files. Those files have to be sorted, otherwise tests will fail with hard to debug issues.
This PR adds a custom entrypoint for the snmp container, which will first assert the validity of those fixture files and then run `snmpsimd.py`

Add a validator for snmprec file

---

dd-trace-py/Dockerfile

Rather than manually adding "stretch" on an image that has know become "buster"
based, specify the right image tag and just update/install packages.

fix(dd-trace-py): specify the right image tag

---

README.md
chef-kitchen/systemd/opensuse/Dockerfile

Add a new OpenSUSE image with a fake systemd for kitchen docker tests on CircleCI.
The puppet datadog agent role tests the role against OpenSUSE Leap.

Add OpenSUSE systemd image

---

README.md
ansible/2.10/centos/Dockerfile
ansible/2.10/debian/Dockerfile
ansible/2.9/centos/Dockerfile
ansible/2.9/debian/Dockerfile

Adds images for the ansible-datadog CI, with Ansible 2.9 and Ansible 2.10, running on Python 3.

[ansible] Add Ansible 2.9 and 2.10 images

---

README.md
voltdb/10.0/Dockerfile
voltdb/10.0/deployment.xml
voltdb/10.0/docker-entrypoint.sh

Add a Dockerfile for VoltDB 10.0.
**Motivation**: we test integrations using Docker, but starting 10+ VoltDB doesn't provide community images anymore, so we built this for our own use in `integrations-core` testing.
**Note**: this image has already been pushed to DockerHub, and it is already being used successfully in https://github.com/DataDog/integrations-core/pull/7973.

Add image for VoltDB 10.0

---

chef-kitchen/systemd/centos6/Dockerfile

The main repos no longer work since CentOS 6 is EOL.
Already pushed to dockerhub. 
Fixes the tests: https://github.com/DataDog/chef-datadog/pull/768

Enable vault repos in chef-kitchen CentOS 6 image

---

ansible/2.10/debian/Dockerfile
ansible/2.6/debian/Dockerfile
ansible/2.7/debian/Dockerfile
ansible/2.8/debian/Dockerfile
ansible/2.9/debian/Dockerfile

* The 2.6, 2.7 and 2.8 are now pinned to stretch. This is because ansible-datadog CI needs them to have Python 2 installed https://github.com/DataDog/ansible-datadog/blob/master/.circleci/config.yml#L137
* The 2.9 and 2.10 are now moved to the newly released bullseye

[ansible] Update buster to bullseye, replace oldstable with stretch

---

README.md
sqlserver/windows/Dockerfile_2016
sqlserver/windows/Dockerfile_2017
sqlserver/windows/Dockerfile_2019
sqlserver/windows/README.md

Add SQL Server windows containers for versions 2016, 2017, 2019. These will be used for windows integration tests for our SQL Server integration.

add sqlserver windows containers for versions 2016, 2017, 2019

---

chef-kitchen/systemd/amazonlinux2/Dockerfile
chef-kitchen/systemd/centos6/Dockerfile
chef-kitchen/systemd/centos7/Dockerfile
chef-kitchen/systemd/centos8/Dockerfile
chef-kitchen/systemd/opensuse/Dockerfile
chef-kitchen/systemd/rocky8/Dockerfile
chef-kitchen/systemd/scripts/0.1/Dockerfile

This PR changes every chef-kitchen Dockerfile maintainers to `Agent Platform <team-agent-platform@datadoghq.com>` because it makes more sense today.

Change chef-kitchen Dockerfile maintainers to Agent Platform

---

README.md
chef-kitchen/apt/debian8/Dockerfile
chef-kitchen/apt/debian8/gpgvnoexpkeysig

The Debian Jessie GPG key expired on Sat Nov 19 2022 21:01:13 GMT+0000. This PR uses gpgv wrapper that ignores key expiration date but checks package signatures such as [this PR](https://github.com/DataDog/datadog-agent-buildimages/pull/319).

Debian 8 (Jessie) image GPG key workaround for apt

---

sqlserver/windows/Dockerfile_2022

Needed to run sqlserver tests on windows 22, which is part of the effort to migrate sqlserver integrations CI from azure pipelines to github actions

Add docker file for sqlserver on windows 22 image

---

ansible/2.6/debian/Dockerfile
ansible/2.7/debian/Dockerfile
ansible/2.8/debian/Dockerfile

Debian Stretch packages are now only available in the Debian Archive, so point our older image repos there.

[ansible] Update Debian stretch repos to use Debian Archive

---

dd-trace-php/Dockerfile_fpm

Updates an old image (4 years) that started to fall apart just over night by rebuilding and add `jq` to the image so we do not need to do this in CI every single time. `rpmlint` does not exists anymore in this Debian release but it seems we do not need it anyway
I pushed the resulting image already and have it in a feature branch at this PR https://github.com/DataDog/dd-trace-php/pull/2048
If everything is okay, I'll merge, create the image and push to the original tag.
Related to: https://github.com/DataDog/dd-trace-php/pull/2044

add `jq` and remove `rpmlint` which is not used

---

chef-kitchen/apt/debian8/Dockerfile

Debian8 (Jessie) is out of support and some packages are not available anymore in standard package stores. This image is used in the kitchen test of https://github.com/DataDog/chef-datadog/ and apt-get update fails if we don't fetch packages from archive sources

Update image to be able to fetch correctly packages

---

README.md
linux-agent-install-script/SLES11/Dockerfile

Add an Image used by the [Agent Linux Install Script](https://github.com/DataDog/agent-linux-install-script) to tests SLES 11.

[Linux Install Script] Add an image to tests for older openSUSE system like SLES11

---

ansible/amazonlinux2/Dockerfile
ansible/suse/Dockerfile

Add `tar` to the AL2 and Centos images, otherwise `action/checkout` fails in Github Actions

Add tar to suse and al2 image to use it in Github Action

---

ansible/debian/Dockerfile

When trying to add [changes](https://github.com/DataDog/ansible-datadog/pull/515/files) in the ci_test done on ansible-datadog repo, I face [issues](https://app.circleci.com/pipelines/github/DataDog/ansible-datadog/840/workflows/4ff5cf0a-6441-458a-ad48-4056ca465e9c/jobs/63407) with circleci failing to retrieve git.
It seems [it's the case from the very beginning](https://app.circleci.com/pipelines/github/DataDog/ansible-datadog/838/workflows/a6046527-a118-44ac-b0c8-63db1868603d/jobs/63129?invite=true#step-101-0_177). Trying to add git and ssh to the image to have a coherent behaviour

Add git and openssh-client as required in circleci for basic checkout

---

sqlserver/windows/Dockerfile_2022
sqlserver/windows/README.md

integrations-core/sqlserver tests run on windows-2019 runner. build sqlserver-2022 on windows server 2019 to avoid error 
`The container operating system does not match the host operating system`. 
According to Microsoft [doc](https://learn.microsoft.com/en-us/troubleshoot/sql/general/use-sql-server-in-windows), sqlserver 2022 is supported on windows 2019.

build sqlserver 2022 on windows server 2019

---

ansible/build.sh
ansible/build_python.sh
ansible/debian/Dockerfile
ansible/rocky8/Dockerfile
ansible/suse/Dockerfile

As I discovered while working on https://github.com/DataDog/ansible-datadog/pull/566, we lack tests for newer ansible versions, which relies on the docker images created from this repo. However, Ansible >= 7 requires python >= 3.9 on the controller and Ansible >= 9 requires python >= 3.10 ([reference](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) based on ansible-core versions, 2.14 would correspond to Ansible 7, etc.).
Existing images rely on whatever Python is available in the distro's repos, which varies (I've seen py3.9 and py3.8 at least, I think). Installing newer Python requires building it from source, which is what I'm adding here. For now I'm only adding it to a subset of the images sufficient to add some …

Allow newer ansible versions in some images by installing newer python

---

ansible/2.6/centos/Dockerfile
ansible/2.7/centos/Dockerfile
ansible/2.8/centos/Dockerfile
ansible/centos/Dockerfile

This base image is using the vault repository following the decomission of mirrorlist.centos.org

use a slightly patched ansible image

---

ansible/amazonlinux2023/Dockerfile

The version detection logic we use in ansible isn't compatible with Amazon Linux 2023 so we need an image to add more testing

add an amazonlinux2023 image

---

README.md
chef-kitchen/systemd/centos9/Dockerfile
chef-kitchen/systemd/centos9/start.sh

* Add systemd-enabled CentOS Stream 9 image for kitchen tests
* Base image: https://hub.docker.com/r/trfore/docker-centos9-systemd

Add systemd-enabled CentOS Stream 9 image
